import '@angular/animations';
import '@angular/platform-browser/animations';
import '@angular/animations/browser';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/compiler';
import '@angular/http';
import '@angular/http/testing';
import '@angular/forms';
import '@angular/router';

import 'ng2-slim-loading-bar';
import 'rxjs';
import 'ng2-select';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'font-awesome/css/font-awesome.min.css';
import 'jquery';